### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by slashmili** [slashmili/alchemist.vim#1]
**alchemist_client**
- [x] [get tmp dir](https://docs.python.org/2/library/tempfile.html#tempfile.tempdir)
- [x] add unit test
- [x] set timeout for socket recv
- [x] find the base project dir(finding already running server/looking for mix.exs/...)
- [x] get full path of elixir project directory
- [x] rewrite in elixir (canceled)
- [x] write the autocomplete rules in the client 

**vim plugin**
- [x] support auto complete for erlang modules(they start with `:`) 
- [x] find [a way](https://github.com/fatih/vim-go/blob/master/autoload/go/doc.vim#L140) to show document without creating tmp file
- [x] prevent toggling AnsiEsc
- [x] shift+k on module should show the module document
- [x] parse the current file and find all the `alias` and send it to alchemist
- [x] Detect the module that we are in
- [x] parse the current file and find the imported modules
- [x] Detect the modules that we are in and the alias and imported modules inside the module
- [x] be able to autocomplete current module functions 
- [x] implement `g]` to jump to definition 
- [x] Support alias for erlang module
- [x] support mix commands 
- [x] support completion for :ExDoc
- [x] `iex` integration
- [x] Added omni search results to popupmenu-completion(canceled)
- [ ] showing information about about data type
- [ ] showing Function/Arity Types Information
